### ISSUE TITLE
Respring kills settings

### ISSUE THREAD

**Issue by vpww** [KritantaDev/HomePlusPro#1]
Settings restore to defaults after resprings. Ios 14.3 iphone 11 pro max u0 6.0

**Comment by lichuu** [comment]
also occurring on 12 pro max, 14.3.

**Comment by me-moegan77** [comment]
Also on iPhone XS Max iOS 14.3, Unc0ver 6.0.1

**Comment by miffy4774** [comment]
This issue still exists on unc0ver 6.1.0 on XS Max iOS 14.3

**Comment by cbottome** [comment]
Still happening with dock config on beta 12. IP12ProMax iOS 14.1 Uc0vr 6.1.1.
