### ISSUE TITLE
Error 402: payment required

### ISSUE THREAD

**Issue by ralphieb2t** [KritantaDev/HomePlusPro#10]
Go to kritanta repo, attempt download of HomePlus Pro beta(no previous homeplus pro avail) stops downloading(on Zbra) and asks if you want to return to queue. Although it says error 402 payment required, this is normally a free package, and even if someone was willing to pay it, there is no possible way to pay. 
All ver. Of HomePlus are gone from Chariz repo. Can’t appear to download the .Deb here either.

**Comment by ralphieb2t** [comment]
Was this ever fixed on the Kritanta repo? Or do you have to download it from somewhere else or something. Why is the issue closed without any explanation?

**Comment by 0cyn** [comment]
https://github.com/kritanta-ios-tweaks/HomePlusPro/releases/tag/2.5.4 Available for download here
