### ISSUE TITLE
Creating New Loadouts Doesn't Work

### ISSUE THREAD

**Issue by ki-tty** [KritantaDev/HomePlusPro#2]
12 Mini, 14.3, unc0ver 6.0.1
HomePlus Pro (Beta) 2.0.0-beta1

When pressing "Create" under loadouts, it prompts for a name, I input something, press enter, and no new layout appears.
Also another issue with loadouts, there's a loadout called "PhoneDefault", which seems to be there by default, and attempting to remove it results in a springboard crash. I'm guessing it's not supposed to be there.

**Comment by fattdabbs** [comment]
11 Pro, 14.1 and same thing is happening to me.

**Comment by sohsatoh** [comment]
It's because the permission of /var/mobile/Documents/HomePlus/Loadouts/. 
It is set to root/wheel, but it should mobile/mobile.

cc: @KritantaDev
