### ISSUE TITLE
App Library Freely Moving/Spaced Incorrectly 

### ISSUE THREAD

**Issue by Kosmosnoetos** [KritantaDev/HomePlusPro#4]
When changing the spacing on my Home Screen it also causes the App Library (when enabled) to become free floating. The spacing of the App Library is also affected when changing the spacing of the Home Screen layout. Not sure if there is a way to prevent this or if it is known about already! Thanks for your hard work!!!!

**Comment by Kosmosnoetos** [comment]
Here is a video

**Comment by darkKing88** [comment]
> When changing the spacing on my Home Screen it also causes the App Library (when enabled) to become free floating. The spacing of the App Library is also affected when changing the spacing of the Home Screen layout. Not sure if there is a way to prevent this or if it is known about already! Thanks for your hard work!!!!

Hey so i got a problem where I can’t move my apps around like to the edit them to a different page to the left, i drag them and won’t stay on that page when i release the app it goes back to the page where it was! Do you know how to fix it? Any ideas?
