### ISSUE TITLE
How do you buy this

### ISSUE THREAD

**Issue by megatech1966** [KritantaDev/HomePlusPro#7]

**Comment by megatech1966** [comment]
How do you buy this???

**Comment by grgarside** [comment]
https://chariz.com/buy/homeplus/buy-button-login

**Comment by megatech1966** [comment]
It says it’s not available to purchase

**Comment by 44jost** [comment]
![9265E98A-7CC1-49D5-9E88-32F58AFA1AAF](https://user-images.githubusercontent.com/82361501/117112780-7fb6b980-ad81-11eb-9b9f-74d30c04d36b.png)

**Comment by 44jost** [comment]
https://user-images.githubusercontent.com/82361501/117112964-bf7da100-ad81-11eb-9abb-26a7959eb08e.MP4

**Comment by KevinBlue18** [comment]
You can buy it from their repo at _repo.krit.me_.
